export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST';
export const SUBJECT_LIST_FAILED = 'SUBJECT_LIST_FAILED';
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS';