export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_SUCCESS_ADD = 'SEARCH_SUCCESS_ADD';

export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST';
export const SUBJECT_LIST_FAILED = 'SUBJECT_LIST_FAILED';
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS';

export const FETCH_DOCUMENT_REQUEST = 'FETCH_DOCUMENT_REQUEST';
export const FETCH_DOCUMENT_FAILED = 'FETCH_DOCUMENT_FAILED';
export const FETCH_DOCUMENT_SUCCESS = 'FETCH_DOCUMENT_SUCCESS';